# Generated by Django 5.0.6 on 2024-05-11 16:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=api.models.user_directory_path),
        ),
    ]
